stages:
  - build_staging
  - build_production

variables:
  REGISTRY_URL: $CI_REGISTRY_IMAGE
  VERSION_FILE: "versions.txt"

before_script:
  - export VERSION=$(if [ -n "$CI_COMMIT_TAG" ]; then echo $CI_COMMIT_TAG; else echo $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA; fi)

build_staging:
  stage: build_staging
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $REGISTRY_URL:$VERSION-staging .
    - docker push $REGISTRY_URL:$VERSION-staging
    - docker tag $REGISTRY_URL:$VERSION-staging $REGISTRY_URL:latest-staging
    - docker push $REGISTRY_URL:latest-staging
  only:
    - main

build_production:
  stage: build_production
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $REGISTRY_URL:$VERSION-production .
    - docker push $REGISTRY_URL:$VERSION-production
    - docker tag $REGISTRY_URL:$VERSION-production $REGISTRY_URL:latest-production
    - docker push $REGISTRY_URL:latest-production
  only:
    - main
  when: manual
